name: Cleanup Old Container Packages

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete old container images
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'alpine'  # Just the package name without organization
          owner: 'hhftechnology'  # Your organization name
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: false
          num-old-versions-to-delete: 10  # Number of old versions to delete per run
