name: Cleanup Old Container Packages

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete old container images
        uses: actions/delete-package-versions@v4
        with:
          package-name: '${{ github.repository }}'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: false
          age-filter: >1  # Deletes packages older than 1 day